# Generated by Django 5.2.13 on 2026-04-15 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RadarScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("s3_key", models.CharField(max_length=255, unique=True)),
                ("scan_time", models.DateTimeField(db_index=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("local_path", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "ordering": ["-scan_time"],
            },
        ),
        migrations.CreateModel(
            name="RadarStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=2)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("elevation", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("region", models.CharField(blank=True, max_length=50)),
                ("last_scan_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["state", "code"],
            },
        ),
        migrations.CreateModel(
            name="MRMSTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("reflectivity", "Merged Reflectivity QC"),
                            ("precip_type", "Precipitation Type"),
                            ("mesh", "MESH Hail 60-min Max"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valid_time", models.DateTimeField(db_index=True)),
                ("s3_key", models.CharField(max_length=500, unique=True)),
                ("tile_path", models.CharField(blank=True, max_length=500)),
                ("bounds_json", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-valid_time"],
                "indexes": [
                    models.Index(
                        fields=["product", "-valid_time"],
                        name="radar_mrmst_product_059af3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NWSAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.CharField(max_length=255, unique=True)),
                ("event", models.CharField(max_length=100)),
                ("severity", models.CharField(max_length=20)),
                ("headline", models.TextField()),
                ("description", models.TextField(blank=True)),
                ("instruction", models.TextField(blank=True)),
                ("area_desc", models.TextField()),
                ("sent", models.DateTimeField()),
                ("effective", models.DateTimeField()),
                ("expires", models.DateTimeField(db_index=True)),
                ("onset", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=20)),
                ("message_type", models.CharField(max_length=20)),
                ("geojson", models.JSONField(blank=True, null=True)),
                ("nws_office", models.CharField(blank=True, max_length=10)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-sent"],
                "indexes": [
                    models.Index(
                        fields=["expires"], name="radar_nwsal_expires_80dbbf_idx"
                    ),
                    models.Index(
                        fields=["event", "expires"], name="radar_nwsal_event_08706f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HailReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valid_time", models.DateTimeField()),
                ("max_mesh_mm", models.FloatField()),
                ("geojson", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radar.radarscan",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="radarscan",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="radar.radarstation"
            ),
        ),
        migrations.CreateModel(
            name="ActiveStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radar.radarstation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RadarTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        choices=[
                            ("reflectivity", "Reflectivity"),
                            ("velocity", "Velocity"),
                            ("mesh", "MESH Hail"),
                            ("nowcast_00", "Nowcast +0min"),
                            ("nowcast_15", "Nowcast +15min"),
                            ("nowcast_30", "Nowcast +30min"),
                            ("nowcast_45", "Nowcast +45min"),
                            ("nowcast_60", "Nowcast +60min"),
                        ],
                        max_length=20,
                    ),
                ),
                ("valid_time", models.DateTimeField()),
                ("tile_path", models.CharField(max_length=500)),
                ("bounds_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="radar.radarscan",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="radarscan",
            index=models.Index(
                fields=["station", "-scan_time"], name="radar_radar_station_c5da1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activestation",
            index=models.Index(
                fields=["expires_at"], name="radar_activ_expires_d54dcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="radartile",
            index=models.Index(
                fields=["product", "-valid_time"], name="radar_radar_product_063124_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="radartile",
            unique_together={("scan", "product")},
        ),
    ]
